import SideBar from "@/components/SideBar";
import "../globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body className="flex p-10 gap-10">
        <SideBar />
        <div className="w-full">{children}</div>
      </body>
    </html>
  );
}
